import { Terminal } from 'lucide-react';

export function CodeBlock({ title, code, language }: { title?: string, code?: string, language?: string }) {
  const defaultCode = `// Autogenerated Engine Core
export class RegionalRouter {
  public async computeVariance(target: number, current: number): Promise<string> {
    const delta = ((current - target) / target) * 100;
    return delta > 0 ? \`+\${delta.toFixed(1)}%\` : \`\${delta.toFixed(1)}%\`;
  }
}`;

  return (
    <div className="bg-[#050505] border border-[hsl(var(--border))] rounded-2xl overflow-hidden h-full shadow-lg shadow-black/40 flex flex-col">
      <div className="px-4 py-3 border-b border-[hsl(var(--border))] flex items-center justify-between bg-[hsl(var(--card))] shrink-0">
        <h3 className="text-[11px] font-mono text-[hsl(var(--muted-foreground))] uppercase tracking-wider flex items-center gap-2">
          <Terminal size={14} />
          {title || "core_engine.ts"}
        </h3>
        <span className="text-[10px] text-violet-400 font-mono bg-violet-400/10 px-2 py-0.5 rounded border border-violet-500/20">{language || "TypeScript"}</span>
      </div>
      <div className="p-5 overflow-x-auto text-[13px] font-mono text-emerald-400 opacity-90 leading-relaxed flex-1 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')]">
        <pre>
          <code>{code || defaultCode}</code>
        </pre>
      </div>
    </div>
  );
}
